<h4>Q1. A class has 4 students and 3 subjects. Their marks are given below. The examiner announces a
subject-wise bonus of 5, 2 and 8 marks respectively. Add the bonus to every student in one line using
broadcasting, then cap any mark above 100 back to 100 and report how many marks had to be capped.

In [1]:
import numpy as np
marks = np.array([
    [92, 99, 95],
    [78, 85, 94],
    [88, 90, 89],
    [96, 95, 93]
])
bonus = np.array([5, 2, 8])
updated_marks = marks + bonus
capped_count = np.sum(updated_marks > 100)
final_marks = np.clip(updated_marks, a_min=None, a_max=100)

print(final_marks)
print(capped_count)

[[ 97 100 100]
 [ 83  87 100]
 [ 93  92  97]
 [100  97 100]]
5


<h4>Q2. Create a 5x5 matrix with a border of 1s and 0s inside, without writing the matrix out by hand.

In [4]:
matrix = np.ones((5, 5), dtype=int)
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


<h4>Q3. Without running the code, predict the shape of np.arange(30).reshape(5, -1).T. Write your
prediction as a comment, then verify it. Also explain in a comment why np.arange(30).reshape(4,
-1) fails

In [5]:
arr = np.arange(30).reshape(5, -1).T
print( arr.shape)

(6, 5)


<h4>Q4. Two arrays of size 4 are given. First join them with hstack and print the shape. Then, using the
same two arrays, build a proper (4, 2) two-column table. In a comment, state why the first attempt did
not produce two columns.
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

In [6]:
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])
h_stacked = np.hstack((heights, weights))
print( h_stacked)
print(h_stacked.shape)
table = np.column_stack((heights, weights))
print( table)
print( table.shape)

[172 158 181 166  68  52  84  59]
(8,)
[[172  68]
 [158  52]
 [181  84]
 [166  59]]
(4, 2)


<h4>Q5. Given a 1D array of 12 monthly sales figures, reshape it into 4 quarters of 3 months each and find
which quarter (index) had the highest average sales, along with that average.
sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])

In [8]:
sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])
quarters = sales.reshape(4, 3)
quarterly_averages = quarters.mean(axis=1)
best_quarter_idx = quarterly_averages.argmax()
highest_average = quarterly_averages[best_quarter_idx]

print( quarters)
print( quarterly_averages)
print(best_quarter_idx )
print(highest_average)

[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]]
[117.66666667 175.          95.         212.66666667]
3
212.66666666666666


<h4>Q6. Build a 3x3 multiplication table from the array below using broadcasting only. Do not use loops and
do not use np.outer — reshape one of the operands so that broadcasting produces the grid.
a = np.array([2, 3, 4])

In [9]:
a = np.array([2, 3, 4])
multiplication_table = a[:, np.newaxis] * a
print( multiplication_table)

[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]


<h4>Q7. Create an array of numbers from 1 to 20 and replace every multiple of 3 with -1.

In [10]:
arr = np.arange(1, 21)
arr[arr % 3 == 0] = -1

print( arr)

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


<h4>Q8. For the matrix below, scale every column into the 0 to 1 range using column-wise min-max
normalization (x - col_min) / (col_max - col_min). Use broadcasting only — no loops. Verify that
each column of the result has a minimum of 0 and a maximum of 1.
X = np.array([[ 50, 1200, 3],
 [ 80, 1500, 9],
 [ 65, 900, 5],
 [ 95, 2000, 7]])

In [11]:
X = np.array([
    [ 50, 1200, 3],
    [ 80, 1500, 9],
    [ 65,  900, 5],
    [ 95, 2000, 7]
])
col_min = X.min(axis=0)
col_max = X.max(axis=0)
X_scaled = (X - col_min) / (col_max - col_min)
scaled_min = X_scaled.min(axis=0)
scaled_max = X_scaled.max(axis=0)

print( np.round(X_scaled, 4))
print(scaled_min)
print( scaled_max)
print( np.allclose(scaled_min, 0) and np.allclose(scaled_max, 1))

[[0.     0.2727 0.    ]
 [0.6667 0.5455 1.    ]
 [0.3333 0.     0.3333]
 [1.     1.     0.6667]]
[0. 0. 0.]
[1. 1. 1.]
True


<h4>Q9. Award medals to the scores below using nested np.where: 'Gold' for 90 and above, 'Silver' for 75
and above, 'Bronze' for 60 and above, and 'None' otherwise. Then count how many students received
each medal.
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

In [12]:
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])
medals = np.where(scores >= 90, 'Gold',
         np.where(scores >= 75, 'Silver',
         np.where(scores >= 60, 'Bronze', 'None')))
unique_medals, counts = np.unique(medals, return_counts=True)
medal_counts = dict(zip(unique_medals, counts))
print( scores)
print( medals)
for medal, count in medal_counts.items():
    print(medal,count)

[94 61 77 45 90 88 59 72]
['Gold' 'Bronze' 'Silver' 'None' 'Gold' 'Silver' 'None' 'Bronze']
Bronze 2
Gold 2
None 2
Silver 2


<h4>Q10. Given the matrix below, use np.where with a single condition to obtain the row and column indices
of every element greater than 50, print those elements, and then replace them with 0 in a copy of the
matrix while leaving the original untouched.
m = np.array([[10, 80, 45],
 [55, 20, 99],
 [70, 33, 12]])

In [13]:
m = np.array([
    [10, 80, 45],
    [55, 20, 99],
    [70, 33, 12]
])
rows, cols = np.where(m > 50)
elements = m[rows, cols]
print( rows)
print( cols)
print(elements)
m_copy = m.copy()
m_copy[rows, cols] = 0

print( m_copy)
print( m)

[0 1 1 2]
[1 0 2 0]
[80 55 99 70]
[[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]
[[10 80 45]
 [55 20 99]
 [70 33 12]]


<h4>Q11. Three sensors each recorded 5 readings. Stack them so that each sensor becomes a row, and
separately stack them so that each sensor becomes a column. Print both shapes and confirm that one
is the transpose of the other.
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

In [14]:
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])
row_stacked = np.vstack((s1, s2, s3))
col_stacked = np.column_stack((s1, s2, s3))
print( row_stacked)
print( row_stacked.shape)

print( col_stacked)
print( col_stacked.shape)

print(np.array_equal(row_stacked.T, col_stacked))

[[12 15 11 19 14]
 [22 18 25 21 20]
 [31 35 29 33 30]]
(3, 5)
[[12 22 31]
 [15 18 35]
 [11 25 29]
 [19 21 33]
 [14 20 30]]
(5, 3)
True


<h4>Q12. Create a random 6x6 matrix with seed = 1 and values between 1 and 100, then find the row-wise
maximum and the column-wise minimum.

In [15]:
np.random.seed(1)
matrix = np.random.randint(1, 101, size=(6, 6))
row_max = matrix.max(axis=1)
col_min = matrix.min(axis=0)

print( matrix)
print( row_max)
print( col_min)

[[38 13 73 10 76  6]
 [80 65 17  2 77 72]
 [ 7 26 51 21 19 85]
 [12 29 30 15 51 69]
 [88 88 95 97 87 14]
 [10  8 64 62 23 58]]
[76 80 85 69 97 64]
[ 7  8 17  2 19  6]


<h4>Q13. A and B are both 2x3 matrices. Compute A @ B.T and A.T @ B. Print the shape of each result and
explain in a comment why both multiplications are legal while A @ B is not.
A = np.array([[1, 2, 3],
 [4, 5, 6]])
B = np.array([[7, 8, 9],
 [1, 0, 2]])
 

In [16]:


A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[7, 8, 9],[1, 0, 2]])
res1 = A @ B.T
res2 = A.T @ B
print( res1)
print( res1.shape)
print( res2)
print( res2.shape)



[[ 50   7]
 [122  16]]
(2, 2)
[[11  8 17]
 [19 16 28]
 [27 24 39]]
(3, 3)


<h4>Q14. Build a complete multi-step pipeline. Starting from the two arrays below: convert them into column
vectors, join them into a single two-column table, attach a third column holding each row's total, then
multiply the three-column table by w = [0.5, 0.2, 0.3] to obtain one score per row. Finally use
np.where to mark each score as 1 if it is above the average score and 0 otherwise. Report the shape of
every intermediate array.
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

In [17]:
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])
w = np.array([0.5, 0.2, 0.3])
hours_col = hours.reshape(-1, 1)
attendance_col = attendance.reshape(-1, 1)
print(hours_col.shape, attendance_col.shape)

table_2col = np.hstack((hours_col, attendance_col))
print( table_2col.shape)

row_totals = np.sum(table_2col, axis=1, keepdims=True)
print( row_totals.shape)

table_3col = np.hstack((table_2col, row_totals))
print(table_3col.shape)

scores = table_3col @ w
print( scores.shape)

avg_score = np.mean(scores)
binary_labels = np.where(scores > avg_score, 1, 0)
print( binary_labels.shape)


print( scores)
print( avg_score)
print( binary_labels)

(6, 1) (6, 1)
(6, 2)
(6, 1)
(6, 3)
(6,)
(6,)
[29.1 52.4 39.  57.  32.4 48.1]
43.0
[0 1 0 1 0 1]


<h4>Q16. Take the array below and create two 1D versions of it — one with flatten() and one with
ravel(). Change the first element of each, then print the original matrix. Explain the difference you
observe in a comment.
m = np.array([[4, 8, 15],
 [16, 23, 42]])

In [18]:
m = np.array([[4, 8, 15],[16, 23, 42]])
flat = m.flatten()
flat[0] = 999
m_reset = m.copy()
rav = m.ravel()
rav[0] = 999
print( flat)
print( rav)
print( m)

[999   8  15  16  23  42]
[999   8  15  16  23  42]
[[999   8  15]
 [ 16  23  42]]


<h4>Q17. 28 daily temperature readings are given. Reshape them into 4 weeks of 7 days, then: find each
week's average, identify the hottest week, and count how many individual days crossed 35 degrees.
np.random.seed(7)
temps = np.random.randint(15, 41, 28

In [19]:
np.random.seed(7)
temps = np.random.randint(15, 41, 28)

weeks = temps.reshape(4, 7)
weekly_averages = weeks.mean(axis=1)
hottest_week_idx = weekly_averages.argmax()
days_above_35 = np.sum(temps > 35)

print( weeks)
print( weekly_averages)
print( days_above_35)

[[30 19 40 37 18 34 38]
 [22 40 29 38 23 40 29]
 [25 23 22 21 19 31 22]
 [27 15 26 38 21 34 27]]
[30.85714286 31.57142857 23.28571429 26.85714286]
7


<h4>Q18. Create two random 3x3 matrices A and B, compute A @ B and B @ A, and check whether the two
results are equal. State your conclusion about matrix multiplication in a comment.

In [20]:
np.random.seed(42)
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))
AB = A @ B
BA = B @ A
is_equal = np.array_equal(AB, BA)

print( A)
print( B)
print( AB)
print( BA)
print( is_equal)

[[7 4 8]
 [5 7 3]
 [7 8 5]]
[[4 8 8]
 [3 6 5]
 [2 8 6]]
[[ 56 144 124]
 [ 47 106  93]
 [ 62 144 126]]
[[124 136  96]
 [ 86  94  67]
 [ 96 112  70]]
False


<h4>Q19. Given the marks matrix below (5 students x 4 subjects), first replace every mark below 35 with 35,
then compute each student's total, and finally print the index of the topper along with their total.
marks = np.array([[45, 28, 67, 80],
 [33, 90, 55, 41],
 [72, 66, 30, 58],
 [88, 79, 91, 84],
 [25, 40, 38, 52]])

In [ ]:
marks = np.array([[45, 28, 67, 80],[33, 90, 55, 41],[72, 66, 30, 58],[88, 79, 91, 84],[25, 40, 38, 52]])

updated_marks = np.clip(marks, a_min=35, a_max=None)

totals = updated_marks.sum(axis=1)

topper_index = totals.argmax()
topper_total = totals[topper_index]

print("Updated Marks:\n", updated_marks)
print("\nStudent Totals:", totals)
print("Topper Index:", topper_index)
print("Topper Total:", topper_total)

<h4>Q20. Start from arr = np.arange(1, 11). Create one variable using a plain slice arr[2:6] and
another using arr[2:6].copy(). Change the first element of each to 999, then print the original array
and explain in a comment which change survived and why.

In [21]:
arr = np.arange(1, 11)
view_slice = arr[2:6]
copy_slice = arr[2:6].copy()
view_slice[0] = 999
copy_slice[0] = 999
print("Original Array:", arr)

Original Array: [  1   2 999   4   5   6   7   8   9  10]
