<h4>Q1. Create an array of the first 12 odd numbers using a single np.arange call.

In [1]:
import numpy as np
odd_numbers = np.arange(1, 24, 2)
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


<h4>Q2. Using np.linspace, create 9 equally spaced values from 5 to 45. Before running, predict the gap
between consecutive values - then verify.

In [2]:
values = np.linspace(5, 45, 9)
gap = values[1] - values[0]
print( values)
print(gap)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
5.0


<h4>Q3. Create np.arange(1, 10) and np.linspace(1, 9, 9). Print both and compare their dtype. Why are
they different?

In [3]:
arr1 = np.arange(1, 10)
arr2 = np.linspace(1, 9, 9)

print( arr1, arr1.dtype)
print( arr2, arr2.dtype)

[1 2 3 4 5 6 7 8 9] int64
[1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


<h4> Create a 6x6 identity matrix with integer dtype - the output must show no decimal points.

In [4]:
identity_matrix = np.eye(6, dtype=int)
print(identity_matrix)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


<h4>Q5. Create a 3x4 matrix where every element is 5, and report its shape, size, and ndim.

In [5]:
matrix = np.full((3, 4), 5)

print( matrix)
print( matrix.shape)
print( matrix.size)
print( matrix.ndim)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(3, 4)
12
2


<h4>Q7. Predict the exact output of np.array([10.9, 25.5, 39.99]).astype(int) before running it. What rule
does the result prove?

In [6]:
arr = np.array([10.9, 25.5, 39.99]).astype(int)
print(arr)

[10 25 39]


<h4>Q8. Given arr = np.arange(10, 101, 10) - extract: (a) the 4th element, (b) the last element using
negative indexing, (c) the 2nd-last element.

In [7]:
arr = np.arange(10, 101, 10)
fourth_element = arr[3]
last_element = arr[-1]
second_last_element = arr[-2]
print( arr)
print( fourth_element)
print( last_element)
print( second_last_element)

[ 10  20  30  40  50  60  70  80  90 100]
40
100
90


<h4>Q9. From the same arr, slice out exactly [30 40 50 60], and separately produce the full array in
reverse

In [8]:
arr = np.arange(10, 101, 10)
subset = arr[2:6]
reversed_arr = arr[::-1]

print( subset)
print( reversed_arr)

[30 40 50 60]
[100  90  80  70  60  50  40  30  20  10]


<h4>Q10. Given arr = np.arange(1, 21) - extract every 3rd element starting from index 1 (result: 2, 5, 8,
...).

In [9]:
arr = np.arange(1, 21)
result = arr[1::3]
print(result)

[ 2  5  8 11 14 17 20]


<h4>Q11. Using one slice only, extract everything from arr (1-20) EXCEPT the first two and the last two
elements.

In [10]:
arr = np.arange(1, 21)
result = arr[2:-2]
print(result)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


<h4>Using the matrix below, extract: (a) the 3rd row, (b) the last column, (c) the centre 3x3 block.

In [11]:
m = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
third_row = m[2, :]
last_column = m[:, -1]
centre_block = m[1:4, 1:4]

print( third_row)
print( last_column)
print( centre_block)

[11 12 13 14 15]
[ 5 10 15 20 25]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


<h4>Q13. From the same matrix, extract the four corner elements as a 2x2 array - using step slicing
only.

In [12]:
m = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
corners = m[::4, ::4]
print("Corner elements (2x2):\n", corners)

Corner elements (2x2):
 [[ 1  5]
 [21 25]]


<h4>Q14. From the same matrix, extract every alternate row AND every alternate column at the same
time (the result is 3x3).

In [13]:
m = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
result = m[::2, ::2]
print( result)

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


<h4>Q15. Given the marks array below - (a) extract all marks greater than 60; (b) extract marks between
50 and 80 using two conditions with & (remember the parentheses!).

In [14]:
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
marks_gt_60 = marks[marks > 60]
marks_50_to_80 = marks[(marks >= 50) & (marks <= 80)]
print( marks_gt_60)
print( marks_50_to_80)

[91 77 62 85 70]
[56 77 62 70]
